name: PR Unit Tests

on:
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        package_dir:
          - mount-helper
          - mount-helper-container

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Strongswan For Testing IPSec Service In Unit Tests
      if: ${{ matrix.package_dir == 'mount-helper' }}
      run: sudo apt install -y charon-systemd

    - name: Run Unit Tests for mount helper
      if: ${{ matrix.package_dir == 'mount-helper' }}
      run: sudo make test -C ${{ matrix.package_dir }}

    - name: Run Unit Tests for mount helper container
      if: ${{ matrix.package_dir == 'mount-helper-container' }}
      run: sudo make ut-coverage -C ${{ matrix.package_dir }}

